### PR TITLE
basic math

### LINKED ISSUE #3: Elementary Mathematical Array operations especially matrix multiplication
- [ ] `*` 
- [ ] `+`
- [ ] `-`

This needs to be done such that:
 - If both operations are `NamedDimsArray`s then they must have the same named dimensions.
 - If 1 operand is a `NamedDimsArray`, and one is not, then the answer uses the named dimensions of the one that is provided.
      - This lets you use `a + parent(b)` to add `a` and `b` that have different named dimensions.

 - `*` is special, 
      - for `a * b` then we only require the the the name of the last dimension of `a` needs to match that of the first of `b`.
      - if one of the operands is not a `NamedDimsArray` then the result of the operation will have to insert made up names for one of the dimensions. 
           - Possibly for ease of implementation we should define `names(::AbstractArray)` to return those names.
           - I originally thought `dim1` and `dim2`,  however on further reflection I think that just calling all artificial dimensions `:_` is best.
           - using `dim1` and `dim2` doesn't help much with avoiding named clashes: Consider where `b` has names and `a` does not then the name of ``(a*b*b'*a')` is `(:dim1, :dim2)`. And the mathematically equivalent: `(a*b)*(a*b)'` would get the name `(:dim1, :dim1)`.
            - repairing names of something that has a name `(:_, :_)` by premultiplcation by something with names `(:time, :_)` and post-multiplcation by `(:_, :value)` seems easier if you don't have to workout where (prepositionally) the original dimension that was added was from.
             - We might even want to make `:_` a special case that is an exception to the rule of dimension names must match for `NamedDimArray`-`NamedDimArray` operation.

### PR DESCRIPTION
**Pull request by oxinabox**
This does array math.
Closes #3 

The + and - will likely need to be redone after #4 
since at least `Base` just defined them to call the Broadcasting equiv.
But they are the simple part of this PR, the  complexity is in `*`

### CODE REVIEW

File: src/name_core.jl [hunk 1]
```diff
@@ -110,22 +138,16 @@ function remaining_dimnames_after_dropping(dimnames::Tuple, dropped_dim::Integer
...
     anti_names = identity_namedtuple(map(x->dimnames[x], dropped_dims))
     full_names = identity_namedtuple(dimnames)
 
     # Now we construct a new named tuple, with all the names we want to remove at the start
-    combined_names = merge(anti_names, full_names)
+    combine_names = merge(anti_names, full_names)
     n_skip = length(anti_names)
     ntuple(length(full_names) - n_skip) do ii
-        combined_names[ii + n_skip]  # Skip over the ones we left as the start
+        combine_names[ii + n_skip]  # Skip over the ones we left as the start
```
Comment (nickrobinson251) [inline src/name_core.jl]:
```suggestion
        combined_names[ii + n_skip]  # Skip over the ones we left as the start
```
else confusing with the function of the same name (also needs changing a few lines above)

File: test/functions_math.jl [hunk 2]
```diff
@@ -0,0 +1,133 @@
+using NamedDims
+using NamedDims: matrix_prod_names
+using Test
+
+@testset "+" begin
+    nda = NamedDimsArray{(:a,)}(ones(3))
+
+    @testset "correct" begin
```
Comment (nickrobinson251) [inline test/functions_math.jl]: ...maybe rename this testset, something like "dimension names agree"?

**Comment by nickrobinson251** [comment]
Needs transpose defined to work nicely here?
```julia
julia> A = [-2 3; 4 -9];

julia> nda = NamedDimsArray(A, (:a, :b));

julia> nda'
2×2 LinearAlgebra.Adjoint{Int64,NamedDimsArray{(:a, :b),Int64,2,Array{Int64,2}}}:
 -2   4
  3  -9

julia> nda' * nda'
2×2 Array{Int64,2}:
  16  -44
 -33   93
```

File: README.md [hunk 3]
```diff
@@ -7,3 +7,34 @@
...
+If you perform an operation between another `AbstractArray` and a `NamedDimsArray`, then
+the result will take its names from the `NamedDimsArray`.
+You can use this to bypass the protection,
+ e.g. `NamedDimsArray{(:time,)}(ones(5)) + parent(NamedDimsArray{(:place,)}(ones(5)))`
+ is allowed.
+
+### Partially Named Dimensions (`:_`)
+
+To allow for arrays where only some dimensions have names,
+the name `:_` is treated as a wildcard.
```
Comment (nickrobinson251) [inline README.md]: perhaps advise users against assigning the name `:_`, just noting that it will be given automatically to a dimension that "loses" its name due to soem operation?

Comment (nickrobinson251) [reply README.md]: Also on docs, we should mention that names must be unique (at least for now)

**Comment by oxinabox** [comment]
Here is MWE for no duplicate wildcards.
It mostly works fine,
until you try and access any of the named dimensions.

I think this is an acceptable issue for now really.
But will open an issue if this PR is merged without a fix

```
julia> nda = NamedDimsArray{(:_,:_,:c)}(ones(10,20,30));

julia> nda[c=2]
ERROR: duplicate field name in NamedTuple: "_" is not unique
Stacktrace:
 [1] default_inds(::Tuple{Symbol,Symbol,Symbol}) at /Users/oxinabox/.julia/dev/NamedDims/src/name_core.jl:61
 [2] #order_named_inds#5(::Base.Iterators.Pairs{Symbol,Int64,Tuple{Symbol},NamedTuple{(:c,),Tuple{Int64}}}, ::Function, ::Tuple{Symbol,Symbol,Symbol}) at /Users/oxinabox/.julia/dev/NamedDims/src/name_core.jl:82
 [3] #order_named_inds at ./none:0 [inlined]
 [4] #order_named_inds#19 at /Users/oxinabox/.julia/dev/NamedDims/src/wrapper_array.jl:134 [inlined]
 [5] #order_named_inds at ./none:0 [inlined]
 [6] #getindex#20 at /Users/oxinabox/.julia/dev/NamedDims/src/wrapper_array.jl:143 [inlined]
 [7] (::getfield(Base, Symbol("#kw##getindex")))(::NamedTuple{(:c,),Tuple{Int64}}, ::typeof(getindex), ::NamedDimsArray{(:_, :_, :c),Float64,3,Array{Float64,3}}) at ./none:0
 [8] top-level scope at none:0

julia> sum(nda; dims=:c)
ERROR: duplicate field name in NamedTuple: "_" is not unique
```

File: README.md (hunk 3 above)
Comment (oxinabox) [reply README.md]: done

File: src/name_core.jl [hunk 4]
```diff
@@ -76,6 +88,27 @@ function order_named_inds(dimnames::Tuple; named_inds...)
     return inds
 end
 
+function combine_names(names_a, names_b)
+    # 0-Allocations if inputs are the same
+    # 1-Allocation, if has a `:)_` see  `@btime (()->combine_names((:a, :b), (:a, :_)))()``
```
Comment (iamed2) [inline src/name_core.jl]: Errant `)` in `:)_`?

File: src/name_core.jl [hunk 5]
```diff
@@ -12,25 +24,19 @@ e.g. `dim((:a, :b), :b) == 2`
 If that `name` is not found then `0` is returned.
 """
 function dim(dimnames::Tuple)
-    # Note: This code is runnable at compile time if input is a constant
-    # If modified, make sure to recheck that it still can run at compile time
-    # e.g. via `@code_llvm (()->dim((:a, :b)))()` which should be very short
+    # 0-Allocations see: `@btime (()->dim((:a, :b)))()`
```
[the remark this answers is not in the document]
Comment (oxinabox) [reply src/name_core.jl]: I moved them all to the top of the file in a single explaination

File: src/functions_math.jl [hunk 6]
```diff
@@ -0,0 +1,57 @@
...
+    end
+    @eval function Base.$op(a::AbstractArray, b::NamedDimsArray{L}) where {L}
+        data = $op(a, parent(b))
+        return NamedDimsArray{L}(data)
+    end
+end
+
+
+# Matrix product
+matrix_prod_error(A, B) = throw(DimensionMismatch(
```
[the remark this answers is not in the document]
Comment (oxinabox) [reply src/functions_math.jl]: Good, yes, better.

I also did not like the thing I had.
It is an utter abuse of the type system.
Creating so called Tuple types, that can't ever be instantiated.

We can get rid of it now,
since we are handling the error case seperately.

```
Base.@pure function check_matmul_dims(a::Tuple{Vararg{Symbol}}, b::Tuple{Vararg{Symbol}})
    a_dim = a[end]
    b_dim = b[1]

    if a_dim !== b_dim && a_dim !== :_ && b_dim !== :_
        throw(DimensionMismatch(
            "Cannot take matrix product of arrays with different inner dimension names. $a vs $b"
        ))
    end

    return nothing
end


matmul_names((a1,a2),(b,))=(a1,b)
matmul_names((a1,a2),(b1,b2))=(a1,b2)
matmul_names((a1,),(b1,b2))=(a1,b2)

function determine_matmul_names(names_a, names_b)
    check_matmul_dims(names_a, names_b)
    return matmul_names(names_a, names_b)
end
```

And that is fully performant. Onlty allocating the returned tuple
It generate the code that I say should constant propegate,

```

julia> @btime (()->determine_matmul_names((:foo,), (:foo,:bar)))()
  7.217 ns (1 allocation: 32 bytes)
(:foo, :bar)

julia> @code_typed (()->determine_matmul_names((:baz,:foo), (:foo,:bar)))()
CodeInfo(
1 ─ %1 = (Base.getfield)((:baz, :foo), 1)::Symbol
│   %2 = (Base.getfield)((:foo, :bar), 2)::Symbol
│   %3 = (Core.tuple)(%1, %2)::Tuple{Symbol,Symbol}
└──      return %3
) => Tuple{Symbol,Symbol}
```

One problem.
Your so called `@pure` function is not pure.
String interpolation, calls `print` under the hood.
Print is a _generic function_.
`@pure` functions are not allowed to call _generic_functions_

[the remark this answers is not in the document]
Comment (oxinabox) [reply src/functions_math.jl]: The following checks at compile time,
and generates perfect code_typed

```
function valid_matmul_dims(a::Tuple{Vararg{Symbol}}, b::Tuple{Vararg{Symbol}})
    a_dim = a[end]
    b_dim = b[1]

    return a_dim === b_dim || a_dim === :_ || b_dim === :_
end


matmul_names((a1,a2),(b,))=(a1,b)
matmul_names((a1,a2),(b1,b2))=(a1,b2)
matmul_names((a1,),(b1,b2))=(a1,b2)

function determine_matmul_names(names_a, names_b)
    valid_matmul_dims(names_a, names_b) || throw(DimensionMismatch(
            "Cannot take matrix product of arrays with different inner dimension names. $a vs $b"
        ))
    return matmul_names(names_a, names_b)
end
```

see the lack of exception handling:
```
julia> @btime (()->determine_matmul_names((:foo,), (:foo,:bar)))()
  7.340 ns (1 allocation: 32 bytes)
(:foo, :bar)

julia> @btime (()->determine_matmul_names((:baz,:foo), (:foo,:bar)))()
  7.322 ns (1 allocation: 32 bytes)
(:baz, :bar)

julia> @code_typed (()->determine_matmul_names((:baz,:foo), (:foo,:bar)))()
CodeInfo(
1 ─ %1 = (Base.getfield)((:baz, :foo), 1)::Symbol
│   %2 = (Base.getfield)((:foo, :bar), 2)::Symbol
│   %3 = (Core.tuple)(%1, %2)::Tuple{Symbol,Symbol}
└──      return %3
) => Tuple{Symbol,Symbol}
```

[the remark this answers is not in the document]
Comment (iamed2) [reply src/functions_math.jl]: The old version could identify the new names at compile time, but the new version can't. I think we still need the tuple type hack (at least my reduced version).

File: src/name_core.jl (hunk 5 above)
[the remark this answers is not in the document]
Comment (iamed2) [reply src/name_core.jl]: Doesn't refer to the compile-time-constant output though.

File: src/functions_math.jl (hunk 6 above)
[the remark this answers is not in the document]
Comment (oxinabox) [reply src/functions_math.jl]: Then we do as follows: and put this everywhere we have marked as allocating once.

```
function determine_matmul_names(a, b)
    valid_matmul_dims(a, b) || throw(DimensionMismatch(
            "Cannot take matrix product of arrays with different inner dimension names. $a vs $b"
        ))
    res = matmul_names(a, b)
    compile_time_return_hack(res)
end 

_compile_time_return(::Val{X}) where X = X
compile_time_return_hack(x) = _compile_time_return(Val{x}())
```

Which works,
it is just stupid that it works:

```

julia> @btime (()->determine_matmul_names((:foo,), (:foo,:bar)))()
  1.488 ns (0 allocations: 0 bytes)
(:foo, :bar)

julia> @btime (()->determine_matmul_names((:baz,:foo), (:foo,:bar)))()
  1.246 ns (0 allocations: 0 bytes)
(:baz, :bar)

julia> @code_typed (()->determine_matmul_names((:baz,:foo), (:foo,:bar)))()
CodeInfo(
1 ─     return (:baz, :bar)
) => Tuple{Symbol,Symbol}
```

File: src/name_core.jl (hunk 5 above)
[the remark this answers is not in the document]
Comment (oxinabox) [reply src/name_core.jl]: will fix

File: src/name_core.jl [hunk 7]
```diff
@@ -84,12 +117,7 @@ determine which are not dropped.
 Dimensions indexed with scalars are dropped
 """
 @generated function remaining_dimnames_from_indexing(dimnames::Tuple, inds)
-    # Note: This allocates once, and it shouldn't have to
-    # See: #@btime (()->determine_remaining_dim((:a, :b, :c), (:,390,:)))()
-    # this is because returning tuple of symbols allocates.
-    # See: https://discourse.julialang.org/t/zero-allocation-tuple-subsetting/23122/8
-    # In general this allocation should be optimised out anyway, when not benchmarking
-    # just this.
+    # 1-Allocation see: @btime (()->determine_remaining_dim((:a, :b, :c), (:,390,:)))()
```
Comment (nickrobinson251) [inline src/name_core.jl]:
```suggestion
    # 1-Allocation see: @btime (()->remaining_dimnames_from_indexing((:a, :b, :c), (:, 390, :)))()
```

File: src/name_core.jl [hunk 8]
```diff
@@ -76,6 +110,30 @@ function order_named_inds(dimnames::Tuple; named_inds...)
...
+function combine_names(names_a, names_b)
+    # 0-Allocations if inputs are the same
+    # 0-Allocation, if has a `:_` see  `@btime (()->combine_names((:a, :b), (:a, :_)))()`
+
+    names_a === names_b && return names_a
+
+    # Error message should not include names until it is thrown, as othrwise
+    # the interpolation allocates and slows everything down a lot.
+    err_msg = "Attempted to combine arrays with incompatible dimension names."
+    length(names_a) != length(names_b) && throw(DimensionMismatch(err_msg * "$names_a ≠ $names_b."))
```
Comment (nickrobinson251) [inline src/name_core.jl]:
```suggestion
    length(names_a) != length(names_b) && throw(DimensionMismatch(err_msg * " $names_a ≠ $names_b."))
```

File: src/name_core.jl [hunk 9]
```diff
@@ -76,6 +110,30 @@ function order_named_inds(dimnames::Tuple; named_inds...)
...
 
+function combine_names(names_a, names_b)
+    # 0-Allocations if inputs are the same
+    # 0-Allocation, if has a `:_` see  `@btime (()->combine_names((:a, :b), (:a, :_)))()`
+
+    names_a === names_b && return names_a
+
+    # Error message should not include names until it is thrown, as othrwise
+    # the interpolation allocates and slows everything down a lot.
+    err_msg = "Attempted to combine arrays with incompatible dimension names."
```
Comment (nickrobinson251) [inline src/name_core.jl]:
```suggestion
    err_msg = "Attempted to combine arrays with incompatible dimension names. "
```

**Comment by nickrobinson251** [comment]
Think `permutedims` is not defined correctly
```julia
julia> A = [-2 3; 4 -9]
2×2 Array{Int64,2}:
 -2   3
  4  -9

julia> nda = NamedDimsArray(A, (:a, :b));

julia> permutedims(A, (2, 1))
2×2 Array{Int64,2}:
 -2   4
  3  -9

julia> permutedims(nda, (2, 1))
ERROR: BoundsError: attempt to access (:a, :b)
  at index [4]
Stacktrace:
 [1] macro expansion at /Users/nick/Documents/code/NamedDims.jl/src/name_core.jl:0 [inlined]
 [2] remaining_dimnames_from_indexing(::Tuple{Symbol,Symbol}, ::Tuple{Int64,CartesianIndex{0},Int64,CartesianIndex{0}}) at /Users/nick/Documents/code/NamedDims.jl/src/name_core.jl:147
 [3] getindex at /Users/nick/Documents/code/NamedDims.jl/src/wrapper_array.jl:128 [inlined]
 [4] _permutedims!(::PermutedDimsArray{Int64,2,(2, 1),(2, 1),Array{Int64,2}}, ::NamedDimsArray{(:a, :b),Int64,2,Array{Int64,2}}, ::CartesianIndices{0,Tuple{}}, ::CartesianIndices{0,Tuple{}}, ::CartesianIndices{0,Tuple{}}, ::Int64, ::Int64) at ./permuteddimsarray.jl:229
 [5] _copy!(::PermutedDimsArray{Int64,2,(2, 1),(2, 1),Array{Int64,2}}, ::NamedDimsArray{(:a, :b),Int64,2,Array{Int64,2}}) at ./permuteddimsarray.jl:218
 [6] permutedims!(::Array{Int64,2}, ::NamedDimsArray{(:a, :b),Int64,2,Array{Int64,2}}, ::Tuple{Int64,Int64}) at ./permuteddimsarray.jl:194
 [7] permutedims(::NamedDimsArray{(:a, :b),Int64,2,Array{Int64,2}}, ::Tuple{Int64,Int64}) at ./permuteddimsarray.jl:113
 [8] top-level scope at none:0
```

File: src/functions_math.jl (hunk 6 above)
[the remark this answers is not in the document]
Comment (iamed2) [reply src/functions_math.jl]: Thanks I hate it 👍

**Comment by iamed2** [comment]
Everything I reviewed is approved; the bug Nick identified should be fixed though
