### PR TITLE
2-argument function to help const propagation in broadcasted_names()

### LINKED ISSUE #187: Type instability when broadcasting
I was trying to chase down allocations that appeared in my code when converting from `Array` to `NamedDimsArray`. I think I have found a case where we may be failing to get type-stable code. Here is what I think is a minimal example:
```
julia> using NamedDims, BenchmarkTools

julia> function example(a,b,c,d)
           @. a -= 0.5 * d * b * c
           return a
       end
example (generic function with 1 method)

julia> a = NamedDimsArray{(:z,)}(rand(5));

julia> b = NamedDimsArray{(:z,)}(rand(5));

julia> c = rand();

julia> d = rand();

julia> @btime example($a,$b,$c,$d)
  733.862 ns (10 allocations: 352 bytes)
5-element NamedDimsArray{(:z,), Float64, 1, Vector{Float64}}:
 -1085.0390848895406
 -3944.198097644197
 -4564.398164918389
 -3641.011715928582
 -5293.772958207846
```
Using `Cthulhu.@descend` suggests that the problem is return type not being inferred for `broadcasted_names(bs...)` from inside `copyto!()` here
https://github.com/invenia/NamedDims.jl/blob/2fa07ee7d94f34767db849942828f97ba0232b28/src/broadcasting.jl#L68-L80
even though when I then step into `broadcasted_names()`, the return type is `Core.Const((:z,))`!

I think the example is minimal, because if I remove even the `0.5 *` from `example()`, `@btime` reports zero allocations.

I was using julia-1.6.4 and NamedDims-0.2.41. Any suggestions for fixes or further debugging very welcome!

### PR DESCRIPTION
**Pull request by johnomotani**
Apparently less recursion helps the compiler to const-propagate.

Fixes #187.

### CODE REVIEW

**Comment by johnomotani** [comment]
I don't claim to understand why this works, if anyone does I'd be interested to know!

I originally made a different version that used meta-programming to generate an arbitrary number of `broadcasted_names()` functions with increasing numbers of arguments. For all the cases I tried, only the 2-argument case was needed to get const-propagation to work though. If someone has time to stress-test and find a case that breaks the 'simple' version in this commit, the meta-programming version was:
```
broadcasted_names(bc::Broadcasted) = broadcasted_names(bc.args...)
const unroll_size = 2 
# Create wrapper that handles calls with more arguments than unroll_size
let argnames = Tuple(Symbol("a$i") for i ∈ 1:unroll_size)
    eval(quote
         function broadcasted_names($(argnames...), bs...)
             a_name = broadcasted_names($(argnames...))
             b_name = broadcasted_names(bs...)
             return unify_names_longest(a_name, b_name)
         end
    end)
end
# Create unrolled functions that call broadcasted_names on each argument for numbers of
# arguments up to unroll_size
for n ∈ 2:unroll_size
    argnames = Tuple(Symbol("a$(i)") for i ∈ 1:n)
    names = Tuple(Symbol("a$(i)_name") for i ∈ 1:n)
    func_body = :() 
    for (argname, name) ∈ zip(argnames, names)
        func_body = quote
            $func_body
            $name = broadcasted_names($argname)
        end 
    end 
    eval(quote
        function broadcasted_names($(argnames...))
            $func_body
            return unify_names_longest($(names...))
        end 
    end)
end
broadcasted_names(a::AbstractArray) = dimnames(a)
broadcasted_names(a) = tuple()
```

**Review by mzgubic — APPROVED** [review]
LGTM, thanks for solving this! Could you bump the version please?

File: src/broadcasting.jl [hunk 1]
```diff
@@ -73,10 +73,18 @@ function Base.copyto!(dest::AbstractArray, bc::Broadcasted{NamedDimsStyle{S}}) w
...
 broadcasted_names(bc::Broadcasted) = broadcasted_names(bc.args...)
-function broadcasted_names(a, bs...)
+function broadcasted_names(a, b)
     a_name = broadcasted_names(a)
-    b_name = broadcasted_names(bs...)
+    b_name = broadcasted_names(b)
     return unify_names_longest(a_name, b_name)
 end
+# Including two explicit arguments like this before starting recursion seems to help
+# const-propagation
```
Comment (oxinabox) [inline src/broadcasting.jl:82]:
```suggestion
# Including two explicit arguments like this before starting recursion helps const-propagation
```

File: test/broadcasting.jl [hunk 2]
```diff
@@ -144,3 +144,18 @@ end
...
+if VERSION >= v"1.4"
+    @testset "Regression test against #187 (allocations)" begin
+        # # https://github.com/invenia/NamedDims.jl/issues/187
+        a = NamedDimsArray{(:z,)}(rand(5))
+        b = NamedDimsArray{(:z,)}(rand(5))
+        c = rand()
+        d = rand()
+        @test 0 == @ballocated foo($a, $b, $c, $d)
+    end
+end
```
Comment (oxinabox) [inline test/broadcasting.jl:161]:
```suggestion
@testset "Regression test against allocations in broadcasting #187" begin
    # https://github.com/invenia/NamedDims.jl/issues/187
    a = NamedDimsArray{(:z,)}(rand(5))
    b = NamedDimsArray{(:z,)}(rand(5))
    c = rand()
    d = rand()
    @test_modern 0 == @ballocated foo($a, $b, $c, $d)
end
```

**Review by oxinabox — APPROVED** [review]

**Comment by oxinabox** [comment]
Thanks!

**Comment by johnomotani** [comment]
Thanks for the speedy reviews!
