### PR TITLE
fixes for breakage introduced by recent Julia versions

### LINKED ISSUE #216: Failures on Julia 1.11
On Julia nightly, two examples of failures are:
```julia
julia> using NamedDims, LinearAlgebra

julia> nda = NamedDimsArray(rand(Int8,3,4), (:x, :y))
3×4 NamedDimsArray(::Matrix{Int8}, (:x, :y)):
     → y
↓ x  -102   114  -104   66
      -35    71    56  100
       73  -119  -112   -1

julia> hcat(nda, nda)
ERROR: MethodError: hcat(::NamedDimsArray{(:x, :y), Int8, 2, Matrix{Int8}}, ::NamedDimsArray{(:x, :y), Int8, 2, Matrix{Int8}}) is ambiguous.

Candidates:
  hcat(a::Union{NamedDimsArray{L, T, 1, A} where A<:AbstractVector{T}, NamedDimsArray{L, T, 2, A} where A<:AbstractMatrix{T}} where {L, T}, b::Union{NamedDimsArray{L, T, 1, A} where A<:AbstractVector{T}, NamedDimsArray{L, T, 2, A} where A<:AbstractMatrix{T}} where {L, T}, cs::AbstractVecOrMat...)
    @ NamedDims ~/.julia/packages/NamedDims/pu9Bn/src/cat.jl:37
  hcat(X::Union{Number, AbstractVecOrMat{<:Number}}...)
    @ SparseArrays ~/.julia/dev/julia/usr/share/julia/stdlib/v1.11/SparseArrays/src/sparsevector.jl:1223
  hcat(a::Union{NamedDimsArray{L, T, 1, A} where A<:AbstractVector{T}, NamedDimsArray{L, T, 2, A} where A<:AbstractMatrix{T}} where {L, T}, b::AbstractVecOrMat, cs::AbstractVecOrMat...)
    @ NamedDims ~/.julia/packages/NamedDims/pu9Bn/src/cat.jl:37
  hcat(a::AbstractVecOrMat, b::Union{NamedDimsArray{L, T, 1, A} where A<:AbstractVector{T}, NamedDimsArray{L, T, 2, A} where A<:AbstractMatrix{T}} where {L, T}, cs::AbstractVecOrMat...)
    @ NamedDims ~/.julia/packages/NamedDims/pu9Bn/src/cat.jl:37

Possible fix, define
  hcat(::Union{NamedDimsArray{L, var"#s186", 1, A} where {var"#s186"<:Number, L, A<:AbstractVector{var"#s186"}}, NamedDimsArray{L, var"#s186", 2, A} where {var"#s186"<:Number, L, A<:AbstractMatrix{var"#s186"}}}, ::Union{NamedDimsArray{L, var"#s186", 1, A} where {var"#s186"<:Number, L, A<:AbstractVector{var"#s186"}}, NamedDimsArray{L, var"#s186", 2, A} where {var"#s186"<:Number, L, A<:AbstractMatrix{var"#s186"}}}, ::Vararg{AbstractVecOrMat{<:Number}})

julia> qr(nda * nda').Q
ERROR: MethodError: no method matching (NamedDimsArray{(:x, :_)})(::LinearAlgebra.QRCompactWYQ{Float64, Matrix{Float64}, Matrix{Float64}})

Closest candidates are:
  (NamedDimsArray{L})(::NamedWrapper{old_names, T, N, A}) where {L, old_names, T, N, A}
   @ NamedDims ~/.julia/dev/NamedDims/src/wrapper_array.jl:70
  (NamedDimsArray{L})(::NamedDimsArray{L}) where L
   @ NamedDims ~/.julia/dev/NamedDims/src/wrapper_array.jl:69
  (NamedDimsArray{L})(::AbstractArray{T, N}) where {L, T, N}
   @ NamedDims ~/.julia/dev/NamedDims/src/wrapper_array.jl:51

Stacktrace:
 [1] getproperty(fact::NamedDims.NamedFactorization{(:x, :x), Float64, LinearAlgebra.QRCompactWY{…}}, d::Symbol)
   @ NamedDims ~/.julia/dev/NamedDims/src/functions_linearalgebra.jl:129
```

Tests on nightly seem not to be running: https://github.com/invenia/NamedDims.jl/actions/workflows/JuliaNightly.yml?query=workflow%3ACI

### PR DESCRIPTION
**Pull request by aplavin**
CI should hopefully pass now!

[ Edit: closes #216 right? ]

### CODE REVIEW

**Comment by aplavin** [comment]
All tests pass, see at https://github.com/aplavin/NamedDims.jl/actions/runs/16301695343/job/46037637119!
(CI doesn't run for PRs for some reason)

**Comment by mcabbott** [comment]
CI had stopped running due to activity. I clicked some buttons...

File: src/cat.jl [hunk 1]
```diff
@@ -28,13 +28,17 @@ end
...
-    (:NamedDimsVecOrMat, :AbstractVecOrMat),
-    (:AbstractVecOrMat, :NamedDimsVecOrMat),
+for (T, S, U) in [
+    (:NamedDimsVecOrMat, :NamedDimsVecOrMat, :AbstractVecOrMat),
+    (:NamedDimsVecOrMat, :AbstractVecOrMat, :AbstractVecOrMat),
+    (:AbstractVecOrMat, :NamedDimsVecOrMat, :AbstractVecOrMat),
+    # needed since Julia 1.10 because of ambiguities introduced by SparseArrays
+    (:(NamedDimsVecOrMat{<:Any,<:Number}), :(NamedDimsVecOrMat{<:Any,<:Number}), :(AbstractVecOrMat{<:Number})),
+    (:(NamedDimsVecOrMat{<:Any,<:Number}), :(AbstractVecOrMat{<:Number}), :(AbstractVecOrMat{<:Number})),
+    (:(AbstractVecOrMat{<:Number}), :(NamedDimsVecOrMat{<:Any,<:Number}), :(AbstractVecOrMat{<:Number})),
```
Comment (mcabbott) [inline src/cat.jl:38]: Sad but probably unavoidable

**Review by mcabbott — APPROVED** [review]
Approved if CI passes

File: src/cat.jl (hunk 1 above)
Comment (aplavin) [reply src/cat.jl:38]: I didn't check if all entries are needed for the tests to pass (probably no), just repeated the same things as above with `<: Number` added.

Idk what the ultimate solution to ambiguities in Julia should be... Note that here in NamedDims ambiguities aren't even related to KeyedArray <-> NamedDims nesting, they are just caused by wanting to overload `v/hcat`.
Although maybe overloading `v/hcat` is not ultimately necessary?.. Didn't explore it.

Comment (mcabbott) [reply src/cat.jl:38]: Do you know if the 3rd loop is required to pass?

I would love there to be a better way than overloading `hcat`. At some point wanted to make Base use `axes` everywhere & then perhaps there's a chance you could introduce some pairwise `promote`-like scheme. But... for now we hack things to keep working?

I thought there was talk of removing the offending SparseArrays methods but it looks like nothing has happened... https://github.com/JuliaSparse/SparseArrays.jl/issues/431  is the relevant thread.

Comment (aplavin) [reply src/cat.jl:38]: Which 3rd loop? Do you mean the one with `reduce` below?

Comment (mcabbott) [reply src/cat.jl:38]: By 3rd I mean the one over U, instead of `cs::AbstractVecOrMat...` before.

~~There were `3^2 == 9` methods, PR currently makes `6^3 == 216` instead. (And 4096 in https://github.com/mcabbott/AxisKeys.jl/pull/169 ) I don't know that this causes any problems but it does seem like a lot!~~

Numbers before these PRs:
```
julia> methods(hcat) |> length  # Base & LinearAlgebra
23

julia> using SparseArrays

julia> methods(hcat) |> length
29

julia> using AxisKeys  # and NamedDims

julia> methods(hcat) |> length
42
```

Comment (aplavin) [reply src/cat.jl:38]: Afaict, it is needed. Note that there's no cartesian product, how do you calculate 216 and 4096?

Comment (mcabbott) [reply src/cat.jl:38]: Oh I'm sorry, you are right. I thought there were 3 nested loops, but clearly there are not.
